# Generated by Django 4.2 on 2023-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_advertisement_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
